"""initial_schema_27_tables

Revision ID: 3aaabeb0e950
Revises: 
Create Date: 2026-07-02 03:50:15.418012
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaabeb0e950'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('audit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('action_at', 'audit_id')
    )
    op.create_table('daily_price',
    sa.Column('price_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('turnover', sa.BigInteger(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('high >= low'),
    sa.CheckConstraint('volume >= 0'),
    sa.PrimaryKeyConstraint('trade_date', 'stock_id'),
    sa.UniqueConstraint('price_id')
    )
    op.create_table('intraday_tick',
    sa.Column('tick_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('tick_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ask_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('bid_volume', sa.BigInteger(), nullable=True),
    sa.Column('ask_volume', sa.BigInteger(), nullable=True),
    sa.Column('tick_type', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price > 0'),
    sa.CheckConstraint('volume >= 0'),
    sa.PrimaryKeyConstraint('tick_time', 'stock_id'),
    sa.UniqueConstraint('tick_id')
    )
    op.create_table('market',
    sa.Column('market_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=40), server_default='Asia/Taipei', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='TWD', nullable=False),
    sa.Column('open_time', sa.Time(), server_default='09:00', nullable=False),
    sa.Column('close_time', sa.Time(), server_default='13:30', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('market_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('strategy',
    sa.Column('strategy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_params', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('strategy_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('system_health',
    sa.Column('health_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('health_id')
    )
    op.create_table('user_account',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('failed_attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('backtest_run',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('parameters', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('cost_model', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('total_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('annual_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('avg_r_multiple', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('metrics_detail', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.strategy_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('data_source_status',
    sa.Column('ds_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('market_id', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='UNKNOWN', nullable=False),
    sa.Column('priority', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('consecutive_failures', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_latency_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], ),
    sa.PrimaryKeyConstraint('ds_id')
    )
    op.create_table('industry',
    sa.Column('industry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], ),
    sa.PrimaryKeyConstraint('industry_id'),
    sa.UniqueConstraint('market_id', 'code')
    )
    op.create_table('market_regime',
    sa.Column('regime_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.SmallInteger(), nullable=False),
    sa.Column('eval_date', sa.Date(), nullable=False),
    sa.Column('regime', sa.String(length=10), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('advance_count', sa.Integer(), nullable=True),
    sa.Column('decline_count', sa.Integer(), nullable=True),
    sa.Column('above_ma20_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('above_ma60_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('above_ma200_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('new_high_count', sa.Integer(), nullable=True),
    sa.Column('new_low_count', sa.Integer(), nullable=True),
    sa.Column('breadth_detail', sa.JSON(), nullable=True),
    sa.Column('intl_data', sa.JSON(), nullable=True),
    sa.Column('gap_prediction', sa.JSON(), nullable=True),
    sa.Column('gap_actual', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], ),
    sa.PrimaryKeyConstraint('regime_id'),
    sa.UniqueConstraint('market_id', 'eval_date')
    )
    op.create_table('schedule_execution',
    sa.Column('exec_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=50), nullable=False),
    sa.Column('market_id', sa.SmallInteger(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], ),
    sa.PrimaryKeyConstraint('exec_id')
    )
    op.create_table('industry_rs',
    sa.Column('rs_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('rs_5d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rs_20d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rs_60d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rank_5d', sa.SmallInteger(), nullable=True),
    sa.Column('rank_20d', sa.SmallInteger(), nullable=True),
    sa.Column('rank_60d', sa.SmallInteger(), nullable=True),
    sa.Column('trend', sa.String(length=10), server_default='FLAT', nullable=False),
    sa.Column('fund_flow_net', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.industry_id'], ),
    sa.PrimaryKeyConstraint('rs_id'),
    sa.UniqueConstraint('industry_id', 'calc_date')
    )
    op.create_table('monte_carlo_result',
    sa.Column('mc_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('num_paths', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('pct_5th_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_25th_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_50th_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_75th_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_95th_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_5th_dd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_25th_dd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_50th_dd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_75th_dd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_95th_dd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('input_win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('input_rr_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('input_risk_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('percentiles', sa.JSON(), nullable=True),
    sa.Column('path_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mc_id')
    )
    op.create_table('stock',
    sa.Column('stock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.SmallInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('listing_type', sa.String(length=10), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('is_disposal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_alert', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_full_cash', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.industry_id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], ),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('market_id', 'symbol')
    )
    op.create_table('walk_forward_result',
    sa.Column('wf_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('window_index', sa.SmallInteger(), nullable=False),
    sa.Column('is_start', sa.Date(), nullable=False),
    sa.Column('is_end', sa.Date(), nullable=False),
    sa.Column('is_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('is_metrics', sa.JSON(), nullable=True),
    sa.Column('oos_start', sa.Date(), nullable=False),
    sa.Column('oos_end', sa.Date(), nullable=False),
    sa.Column('oos_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('oos_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('oos_win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('oos_metrics', sa.JSON(), nullable=True),
    sa.Column('efficiency_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_overfit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wf_id'),
    sa.UniqueConstraint('run_id', 'window_index')
    )
    op.create_table('backtest_trade',
    sa.Column('trade_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=10), server_default='LONG', nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('shares', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('entry_signal', sa.String(length=30), nullable=True),
    sa.Column('exit_signal', sa.String(length=30), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('hold_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_table('conclusion',
    sa.Column('conclusion_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('eval_date', sa.Date(), nullable=False),
    sa.Column('raw_level', sa.SmallInteger(), nullable=False),
    sa.Column('regime_downgrade', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('sentiment_downgrade', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('industry_downgrade', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('adjusted_level', sa.SmallInteger(), nullable=False),
    sa.Column('downgrade_reasons', sa.JSON(), nullable=True),
    sa.Column('module_scores', sa.JSON(), nullable=True),
    sa.Column('layer_signals', sa.JSON(), nullable=True),
    sa.Column('consensus_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.PrimaryKeyConstraint('conclusion_id'),
    sa.UniqueConstraint('stock_id', 'eval_date')
    )
    op.create_table('detector_alert',
    sa.Column('alert_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('detector_type', sa.String(length=30), nullable=False),
    sa.Column('alert_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=10), server_default='INFO', nullable=False),
    sa.Column('price_at_alert', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume_at_alert', sa.BigInteger(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('institutional_flow',
    sa.Column('flow_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('foreign_buy', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('foreign_sell', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('foreign_net', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('trust_buy', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('trust_sell', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('trust_net', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('dealer_buy', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('dealer_sell', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('dealer_net', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_net', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.PrimaryKeyConstraint('flow_id'),
    sa.UniqueConstraint('stock_id', 'trade_date')
    )
    op.create_table('margin_trading',
    sa.Column('margin_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('margin_buy', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('margin_sell', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('margin_balance', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('margin_change', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('short_buy', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('short_sell', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('short_balance', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('short_change', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('short_ratio', sa.Numeric(precision=8, scale=4), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.PrimaryKeyConstraint('margin_id'),
    sa.UniqueConstraint('stock_id', 'trade_date')
    )
    op.create_table('notification_log',
    sa.Column('notif_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message_title', sa.String(length=200), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('notif_id')
    )
    op.create_table('revenue',
    sa.Column('revenue_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('report_year', sa.SmallInteger(), nullable=False),
    sa.Column('report_month', sa.SmallInteger(), nullable=False),
    sa.Column('revenue_amount', sa.BigInteger(), nullable=False),
    sa.Column('mom_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('yoy_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cumulative_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('report_month BETWEEN 1 AND 12'),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.PrimaryKeyConstraint('revenue_id'),
    sa.UniqueConstraint('stock_id', 'report_year', 'report_month')
    )
    op.create_table('scan_result',
    sa.Column('scan_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('scan_date', sa.Date(), nullable=False),
    sa.Column('axis_industry', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('axis_catalyst', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('axis_fund_flow', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('axis_rs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('axis_total', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('tech_verdict', sa.String(length=10), nullable=True),
    sa.Column('fund_verdict', sa.String(length=10), nullable=True),
    sa.Column('chip_verdict', sa.String(length=10), nullable=True),
    sa.Column('positive_count', sa.SmallInteger(), nullable=True),
    sa.Column('aux_confidence', sa.String(length=10), nullable=True),
    sa.Column('aux_detail', sa.JSON(), nullable=True),
    sa.Column('verdict', sa.String(length=10), nullable=False),
    sa.Column('exclude_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.strategy_id'], ),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_table('signal',
    sa.Column('signal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('price_at_signal', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.strategy_id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_table('trade_journal',
    sa.Column('journal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=10), server_default='LONG', nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('stop_loss_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('r_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('entry_reason', sa.Text(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('strategy_used', sa.String(length=30), nullable=True),
    sa.Column('conclusion_at_entry', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_open', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('journal_id')
    )
    op.create_table('watchlist',
    sa.Column('watchlist_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tab_name', sa.String(length=50), server_default='default', nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('watchlist_id'),
    sa.UniqueConstraint('user_id', 'tab_name', 'stock_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('trade_journal')
    op.drop_table('signal')
    op.drop_table('scan_result')
    op.drop_table('revenue')
    op.drop_table('notification_log')
    op.drop_table('margin_trading')
    op.drop_table('institutional_flow')
    op.drop_table('detector_alert')
    op.drop_table('conclusion')
    op.drop_table('backtest_trade')
    op.drop_table('walk_forward_result')
    op.drop_table('stock')
    op.drop_table('monte_carlo_result')
    op.drop_table('industry_rs')
    op.drop_table('schedule_execution')
    op.drop_table('market_regime')
    op.drop_table('industry')
    op.drop_table('data_source_status')
    op.drop_table('backtest_run')
    op.drop_table('user_account')
    op.drop_table('system_health')
    op.drop_table('strategy')
    op.drop_table('market')
    op.drop_table('intraday_tick')
    op.drop_table('daily_price')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
