apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: atlas_prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: '15s'      # match global scrape_interval
      exemplarTraceIdDestinations: []
    version: 1
